### ISSUE TITLE
Assignment 5: Treebook 我也认为有问题，终于遇到同伴了

### ISSUE THREAD

**Issue by rainy-xie** [JiNanPiWang/CS106L#1]
而且assignment6没权限获取代码了.....

**Comment by JiNanPiWang** [comment]
对😂，不过之前4和5都没权限获取，后来放开了，不知道6和7之后会不会放开

**Comment by tianzhang-dev** [comment]
> 而且assignment6没权限获取代码了.....


对😂，不过之前4和5都没权限获取，后来放开了，不知道6和7之后会不会放开

**Comment by rainy-xie** [comment]
那应该会放开的，我再等等

**Comment by tianzhang-dev** [comment]
> 那应该会放开的，我再等等

嗯嗯

**Comment by LexTran** [comment]
assign5 已经更新过了，新的要求是不能实现复制赋值，但是可以有赋值构造，这样就没有问题了

**Comment by tianzhang-dev** [comment]
> assign5 已经更新过了，新的要求是不能实现复制赋值，但是可以有赋值构造，这样就没有问题了

你有时间的话可以提一个pr，我把最新的合并一下
