### ISSUE TITLE
催更！！

### ISSUE THREAD

**Issue by Sunburst7** [JiNanPiWang/CS106L#2]
跪求更新

**Comment by tianzhang-dev** [comment]
> 跪求更新

你觉得有哪里需要更新啊😃，我可以做一下

**Comment by Sunburst7** [comment]
> > 跪求更新
> 
> 你觉得有哪里需要更新啊😃，我可以做一下

就是Assignment 6与7的资源，官网没法下载┭┮﹏┭┮

**Comment by tianzhang-dev** [comment]
> > > 跪求更新
> > 
> > 
> > 你觉得有哪里需要更新啊😃，我可以做一下
> 
> 就是Assignment 6与7的资源，官网没法下载┭┮﹏┭┮

这个我也没找到方法下😂

**Comment by Andy3117006664** [comment]
> > > > 跪求更新
> > > 
> > > 
> > > 你觉得有哪里需要更新啊😃，我可以做一下
> > 
> > 
> > 就是Assignment 6与7的资源，官网没法下载┭┮﹏┭┮
> 
> 这个我也没找到方法下😂

Assignment 6好像开权限了，Assignment 7没开😁

**Comment by tianzhang-dev** [comment]
> > > > > 跪求更新
> > > > 
> > > > 
> > > > 你觉得有哪里需要更新啊😃，我可以做一下
> > > 
> > > 
> > > 就是Assignment 6与7的资源，官网没法下载┭┮﹏┭┮
> > 
> > 
> > 这个我也没找到方法下😂
> 
> Assignment 6好像开权限了，Assignment 7没开😁

可以分享一下assignment6的内容吗，我好像还是看不了😭

**Comment by Andy3117006664** [comment]
[Assignment_6_ExploreCourses.pdf](https://github.com/user-attachments/files/15863932/Assignment_6_ExploreCourses.pdf)

Here

**Comment by tianzhang-dev** [comment]
> [Assignment_6_ExploreCourses.pdf](https://github.com/user-attachments/files/15863932/Assignment_6_ExploreCourses.pdf)
> 
> Here

这个里面的代码你能打开吗

**Comment by Andy3117006664** [comment]
> > [Assignment_6_ExploreCourses.pdf](https://github.com/user-attachments/files/15863932/Assignment_6_ExploreCourses.pdf)
> > Here
> 
> 这个里面的代码你能打开吗

确实不行，兄弟
